targets:
  $default:
    builders:
      build_git_version:
        enabled: true

builders:
  build_git_version:
    import: "package:build_git_version/builder.dart"
    builder_factories: ["buildVersion"]
    build_extensions: {"pubspec.yaml": ["lib/src/version.dart"]}
    defaults:
      options:
        output: "lib/src/version.dart"
    build_to: source
    auto_apply: dependents