name: build_git_version
description: A builder to generate a package version from git tag and commit distance
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  build: ^2.1.0
  build_config: ^1.0.0
  pubspec_parse: ^1.0.0
  git: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_verify: '>=2.0.0 <4.0.0'
  checked_yaml: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
